baseURL = "https://ota.tensevntysevn.cf/"
languageCode = "en-us"
title = "Tensevntysevn OTA Services"

[outputs]
    section = ["rss"]
    page = ["rss"]
title = "TNS OTA Services"

[params]
	donateUrl = ""
