---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: heading
  label: ROMs
- type: directory
  path: content/fresh
  label: Fresh
  create: all
  match: "**/*"
  templates:
  - update-information
  - rom-information
- type: directory
  path: content/freshx
  label: Fresh 3.2+
  create: all
  match: "**/*"
  templates:
  - update-information
  - rom-information
- type: heading
  label: Addons
- type: directory
  path: content/addons/fresh
  label: Addons
  create: all
  match: "**/*"
  templates:
  - addon-information
- type: directory
  path: content/addons/freshx
  label: Fresh 3.2+
  create: all
  match: "**/*"
  templates:
  - addon-information
- type: heading
  label: App Updates
- type: document
  path: data/freshApp.yml
  label: Fresh App
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
