# This is a basic workflow to help you get started with Actions

name: Netlify Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the ota_new branch
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish on SEA Server
        shell: bash
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_SEA }}
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/${DEPLOY_KEY}
          
      - name: Publish on Europe Server
        shell: bash
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_CHILE }}
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/${DEPLOY_KEY}

      - name: Publish on Chile Server
        shell: bash
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_TURKEY }}
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/${DEPLOY_KEY}

      - name: Publish on Amsterdam Server
        shell: bash
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_RUSSIA }}
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/${DEPLOY_KEY}

      - name: Publish on India Server
        shell: bash
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_INDIA }}
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/${DEPLOY_KEY}

      - name: Publish on Global Server
        shell: bash
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_GLOBAL }}
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/${DEPLOY_KEY}

